cluster.name: "rag-cluster"
node.name: "rag-node"
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node

# 内存设置
bootstrap.memory_lock: true

# 索引设置
action.auto_create_index: true
action.destructive_requires_name: true

# 安全设置
xpack.security.enabled: false
xpack.monitoring.enabled: false

# 性能优化
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 20%
indices.fielddata.cache.size: 40%

# 日志设置
logger.level: INFO